repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: sort-simple-yaml
      - id: trailing-whitespace

  # Local hooks
  - repo: local
    hooks:
      - id: checkov
        name: checkov
        entry: mise
        args:
          - run
          - checkov
        language: system
        always_run: true
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: mise
        args:
          - run
          - prettier-write-all
        language: system
        always_run: true
        pass_filenames: false
      - id: markdownlint
        name: markdownlint
        entry: mise
        args:
          - run
          - markdownlint-fix-all
        language: system
        files: '\.md$'
        pass_filenames: false
      - id: hadolint
        name: hadolint
        entry: mise
        args:
          - run
          - hadolint
        language: system
        files: '(Dockerfile|Containerfile)$'
        pass_filenames: true
      - id: actionlint
        name: actionlint
        entry: mise
        args:
          - run
          - actionlint
        language: system
        pass_filenames: false
        always_run: true
      - id: shellcheck
        name: shellcheck
        entry: mise
        args:
          - run
          - shellcheck
        language: system
        pass_filenames: true
        files: '\.sh$'
      - id: rust-fmt-all
        name: rust-fmt-all
        entry: mise
        args:
          - run
          - rust-fmt-all
        language: system
        types: [rust]
        pass_filenames: false

      - id: rust-clippy-all
        name: rust-clippy-all
        entry: mise
        args:
          - run
          - rust-clippy-all
        language: system
        types: [rust]
        pass_filenames: false
